services:
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: magedmohamed/manar-app-web:latest
    container_name: manar-app-web
    ports:
      - "127.0.0.1:8090:80"
    depends_on:
      - backend
    networks:
      - manar-network
    restart: unless-stopped

  backend:
    build: ./backend
    image: magedmohamed/manar-app-backend:latest
    container_name: manar-app-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/manarapp
      - JWT_SECRET=${JWT_SECRET:-manar-app-production-secret-2026}
      - PORT=3000
      - PAYMOB_API_KEY=${PAYMOB_API_KEY:-ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRFNE1qazVOaXdpYm1GdFpTSTZJbWx1YVhScFlXd2lmUS5IdHlNSGZJMVQ4d2lyejJSdGpIb3hqZkVfRGgxYXFJcklfRmdsRmZlOWpoM3d2c1NXekxoUmw4YlF2UGs2QzJCMGwzRnY2T1ZDM3RzaDNSUUtxZUFHUQ==}
      - PAYMOB_INTEGRATION_ID=${PAYMOB_INTEGRATION_ID:-5733856}
      - PAYMOB_IFRAME_ID=${PAYMOB_IFRAME_ID:-1053347}
      - PAYMOB_HMAC_SECRET=${PAYMOB_HMAC_SECRET:-3C0A44BB6AB3D3ECDDD33BEE9FBCFC29}
      - SITE_URL=${SITE_URL:-https://manar.cloud-stacks.com}
    depends_on:
      - mongo
    networks:
      - manar-network
      - monitoring-network
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: manar-app-mongo
    volumes:
      - manar_mongo_data:/data/db
    networks:
      - manar-network
    restart: unless-stopped

networks:
  manar-network:
    driver: bridge
  monitoring-network:
    external: true
    name: devopsacademy_default

volumes:
  manar_mongo_data:
